// Generated by gencpp from file rh_p12_rn_a_base_module_msgs/GetItemValueResponse.msg
// DO NOT EDIT!


#ifndef RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUERESPONSE_H
#define RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rh_p12_rn_a_base_module_msgs
{
template <class ContainerAllocator>
struct GetItemValueResponse_
{
  typedef GetItemValueResponse_<ContainerAllocator> Type;

  GetItemValueResponse_()
    : value(0)  {
    }
  GetItemValueResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetItemValueResponse_

typedef ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<std::allocator<void> > GetItemValueResponse;

typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse > GetItemValueResponsePtr;
typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse const> GetItemValueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator1> & lhs, const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator1> & lhs, const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rh_p12_rn_a_base_module_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d213e8c146065ec958333c617eb1a6";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d213e8c146065eULL;
  static const uint64_t static_value2 = 0xc958333c617eb1a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rh_p12_rn_a_base_module_msgs/GetItemValueResponse";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 value\n"
"\n"
;
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetItemValueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUERESPONSE_H
