// Generated by gencpp from file rh_p12_rn_a_base_module_msgs/GetItemValue.msg
// DO NOT EDIT!


#ifndef RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUE_H
#define RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUE_H

#include <ros/service_traits.h>


#include <rh_p12_rn_a_base_module_msgs/GetItemValueRequest.h>
#include <rh_p12_rn_a_base_module_msgs/GetItemValueResponse.h>


namespace rh_p12_rn_a_base_module_msgs
{

struct GetItemValue
{

typedef GetItemValueRequest Request;
typedef GetItemValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetItemValue
} // namespace rh_p12_rn_a_base_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValue > {
  static const char* value()
  {
    return "7c260e3ee48acb0834abacf55f26ef25";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValue&) { return value(); }
};

template<>
struct DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValue > {
  static const char* value()
  {
    return "rh_p12_rn_a_base_module_msgs/GetItemValue";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValue&) { return value(); }
};


// service_traits::MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest> should match
// service_traits::MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValue >
template<>
struct MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValue >::value();
  }
  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest> should match
// service_traits::DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValue >
template<>
struct DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest>
{
  static const char* value()
  {
    return DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValue >::value();
  }
  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse> should match
// service_traits::MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValue >
template<>
struct MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rh_p12_rn_a_base_module_msgs::GetItemValue >::value();
  }
  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse> should match
// service_traits::DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValue >
template<>
struct DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse>
{
  static const char* value()
  {
    return DataType< ::rh_p12_rn_a_base_module_msgs::GetItemValue >::value();
  }
  static const char* value(const ::rh_p12_rn_a_base_module_msgs::GetItemValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_GETITEMVALUE_H
