// Generated by gencpp from file rh_p12_rn_a_base_module_msgs/WriteCtrlItem.msg
// DO NOT EDIT!


#ifndef RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_WRITECTRLITEM_H
#define RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_WRITECTRLITEM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rh_p12_rn_a_base_module_msgs
{
template <class ContainerAllocator>
struct WriteCtrlItem_
{
  typedef WriteCtrlItem_<ContainerAllocator> Type;

  WriteCtrlItem_()
    : joint_name()
    , item_name()
    , value(0)  {
    }
  WriteCtrlItem_(const ContainerAllocator& _alloc)
    : joint_name(_alloc)
    , item_name(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _joint_name_type;
  _joint_name_type joint_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_name_type;
  _item_name_type item_name;

   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> const> ConstPtr;

}; // struct WriteCtrlItem_

typedef ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<std::allocator<void> > WriteCtrlItem;

typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem > WriteCtrlItemPtr;
typedef boost::shared_ptr< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem const> WriteCtrlItemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator1> & lhs, const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator2> & rhs)
{
  return lhs.joint_name == rhs.joint_name &&
    lhs.item_name == rhs.item_name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator1> & lhs, const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rh_p12_rn_a_base_module_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01627d3668897b31e2f9d3f5dfbcbf76";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01627d3668897b31ULL;
  static const uint64_t static_value2 = 0xe2f9d3f5dfbcbf76ULL;
};

template<class ContainerAllocator>
struct DataType< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rh_p12_rn_a_base_module_msgs/WriteCtrlItem";
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint_name\n"
"string item_name\n"
"uint32 value\n"
;
  }

  static const char* value(const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_name);
      stream.next(m.item_name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteCtrlItem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rh_p12_rn_a_base_module_msgs::WriteCtrlItem_<ContainerAllocator>& v)
  {
    s << indent << "joint_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_name);
    s << indent << "item_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item_name);
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RH_P12_RN_A_BASE_MODULE_MSGS_MESSAGE_WRITECTRLITEM_H
