// Generated by gencpp from file robotis_controller_msgs/SetJointModuleResponse.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETJOINTMODULERESPONSE_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETJOINTMODULERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct SetJointModuleResponse_
{
  typedef SetJointModuleResponse_<ContainerAllocator> Type;

  SetJointModuleResponse_()
    : result(false)  {
    }
  SetJointModuleResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointModuleResponse_

typedef ::robotis_controller_msgs::SetJointModuleResponse_<std::allocator<void> > SetJointModuleResponse;

typedef boost::shared_ptr< ::robotis_controller_msgs::SetJointModuleResponse > SetJointModuleResponsePtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::SetJointModuleResponse const> SetJointModuleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator1> & lhs, const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator1> & lhs, const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/SetJointModuleResponse";
  }

  static const char* value(const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointModuleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::SetJointModuleResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_SETJOINTMODULERESPONSE_H
